#!/usr/bin/env bash
set -e

# tsconfig.json
cat > tsconfig.json <<'JSON'
{
  "compilerOptions": {
    "target": "esnext",
    "lib": ["dom","dom.iterable","esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": { "@components/*": ["src/components/*"], "@styles/*": ["src/styles/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
JSON

# next.config.js
cat > next.config.js <<'JS'
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true
};
module.exports = nextConfig;
JS

# tailwind & postcss
cat > tailwind.config.js <<'JS'
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/app/**/*.{js,ts,jsx,tsx}'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: { puantaj: '#0ea5a4' }
    }
  },
  plugins: []
}
JS

cat > postcss.config.js <<'JS'
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {}
  }
}
JS

# next-env.d.ts
cat > next-env.d.ts <<'TS'
/// <reference types="next" />
/// <reference types="next/types/global" />
/// <reference types="next/image-types/global" />
// NOTE: This file is generated by Next.js — do not edit.
TS

# .gitignore
cat > .gitignore <<'GIT'
node_modules
.next
out
.env
.env.local
.DS_Store
.vscode
coverage
GIT

# styles and pages
mkdir -p src/styles src/pages src/components

cat > src/styles/globals.css <<'CSS'
@tailwind base;
@tailwind components;
@tailwind utilities;

html,body { padding:0; margin:0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial; }
CSS

cat > src/pages/_app.tsx <<'TSX'
import type { AppProps } from 'next/app'
import '../styles/globals.css'
export default function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}
TSX

cat > src/pages/index.tsx <<'TSX'
import Link from 'next/link'
export default function Home() {
  return (
    <main className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900">
      <div className="text-center p-8 bg-white dark:bg-gray-800 rounded shadow">
        <h1 className="text-2xl font-bold mb-4">Puantaj Pro — Hoş geldiniz</h1>
        <p className="mb-4">Bu başlangıç iskeleti. Giriş ve kayıt sayfalarına göz atın.</p>
        <div className="space-x-4">
          <Link href="/login" className="text-puantaj font-semibold">Giriş</Link>
          <Link href="/signup" className="text-gray-600">Kayıt</Link>
        </div>
      </div>
    </main>
  )
}
TSX

cat > src/pages/login.tsx <<'TSX'
import Link from 'next/link'
export default function Login() {
  return (
    <main className="min-h-screen flex items-center justify-center">
      <div className="max-w-md w-full p-6 bg-white dark:bg-gray-800 rounded shadow">
        <h1 className="text-xl font-semibold mb-4">Giriş</h1>
        <form className="space-y-3">
          <input className="w-full p-2 border rounded" placeholder="Email" />
          <input type="password" className="w-full p-2 border rounded" placeholder="Parola" />
          <button className="w-full bg-puantaj text-white py-2 rounded">Giriş Yap</button>
        </form>
        <p className="mt-4 text-sm">Hesabın yok mu? <Link href="/signup" className="text-puantaj">Kayıt ol</Link></p>
      </div>
    </main>
  )
}
TSX

cat > src/pages/signup.tsx <<'TSX'
export default function Signup() {
  return (
    <main className="min-h-screen flex items-center justify-center">
      <div className="max-w-md w-full p-6 bg-white dark:bg-gray-800 rounded shadow">
        <h1 className="text-xl font-semibold mb-4">Kayıt</h1>
        <form className="space-y-3">
          <input className="w-full p-2 border rounded" placeholder="Ad Soyad" />
          <input className="w-full p-2 border rounded" placeholder="Email" />
          <input type="password" className="w-full p-2 border rounded" placeholder="Parola" />
          <button className="w-full bg-puantaj text-white py-2 rounded">Hesap Oluştur</button>
        </form>
      </div>
    </main>
  )
}
TSX

# components
cat > src/components/Header.tsx <<'TSX'
import Link from 'next/link'
export default function Header(){
  return (
    <header className="bg-white dark:bg-gray-900 shadow">
      <div className="container mx-auto px-4 py-3 flex items-center justify-between">
        <Link href="/" className="font-bold text-lg text-puantaj">Puantaj Pro</Link>
        <nav className="space-x-4">
          <Link href="/login" className="text-sm">Giriş</Link>
          <Link href="/signup" className="text-sm">Kayıt</Link>
        </nav>
      </div>
    </header>
  )
}
TSX

cat > src/components/Footer.tsx <<'TSX'
export default function Footer(){
  return (
    <footer className="bg-gray-50 dark:bg-gray-800 text-center text-sm py-6 mt-8">
      © $(date +%Y) Puantaj Pro
    </footer>
  )
}
TSX

cat > src/components/Layout.tsx <<'TSX'
import { ReactNode } from 'react'
import Header from './Header'
import Footer from './Footer'

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Header />
      <main className="min-h-[70vh] container mx-auto px-4 py-8">{children}</main>
      <Footer />
    </>
  )
}
TSX

# ESLint / Prettier / env / README / CI
cat > .eslintrc.js <<'JS'
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  extends: ['next/core-web-vitals', 'plugin:@typescript-eslint/recommended', 'prettier'],
  plugins: ['@typescript-eslint'],
  rules: {}
}
JS

cat > .prettierrc <<'PRE'
{
  "semi": true,
  "singleQuote": true,
  "trailingComma": "all",
  "printWidth": 80,
  "tabWidth": 2
}
PRE

cat > .env.example <<'ENV'
NEXT_PUBLIC_SITE_URL=https://puantaj-source.vercel.app
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=change_me
DATABASE_URL=postgresql://user:pass@localhost:5432/puantaj
ENV

cat > README.md <<'MD'
# puantaj-source

Local geliştirme:
1. npm install
2. cp .env.example .env
3. npm run dev

Deploy: Vercel'e bağlayın, gerekli env değişkenlerini ekleyin.
MD

mkdir -p .github/workflows
cat > .github/workflows/ci.yml <<'YML'
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test --if-present
YML

echo "Scaffold files created."
